version: '3.4'
services:
  bitwarden.public.dappnode.eth:
    image: 'bitwarden.public.dappnode.eth:1.1.0'
    build: ./build
    environment:
      - 'ROCKET_TLS={certs="/bitwarden.crt", key="/bitwarden.key"}'
      - EXTERNAL=false
    volumes:
      - 'data:/data'
    ports:
      - '8343:80'
      - '3012:3012'
volumes:
  data: {}
