version: "3.4"
services:
  bitwarden.public.dappnode.eth:
    image: "bitwarden.public.dappnode.eth:1.1.1"
    build: ./build
    environment:
      - SIGNUPS_ALLOWED=false
    volumes:
      - "data:/data"
    ports:
      - "8343:80"
      - "3012:3012"
volumes:
  data: {}
