version: '3.4'
services:
  dappnode-package-bitwarden.public.dappnode.eth:
    image: 'dappnode-package-bitwarden.public.dappnode.eth:0.1.1'
    build: ./build
    volumes:
      - 'data:/data'
    ports:
      - '8343:80'
      - '3012:3012'
volumes:
  data: {}